import type { QuizModel } from '../../../types/quiz.types';

export const questions: QuizModel.Question[] = [
    // ============================================================
    // LEVEL 1
    // ============================================================
    {
        question: "Where does sushi traditionally come from?",
        options: ["Japan", "Mexico", "India", "Greece"],
        answer: 0,
        explanation: "Sushi is a traditional Japanese food.",
        level: 1,
    },
    {
        question: "Which country is famous for paella?",
        options: ["Spain", "Italy", "France", "Portugal"],
        answer: 0,
        explanation: "Paella originated in Valencia, Spain.",
        level: 1,
    },
    {
        question: "Where did tacos originate?",
        options: ["Mexico", "Brazil", "Argentina", "Peru"],
        answer: 0,
        explanation: "Tacos originated in Mexico.",
        level: 1,
    },
    {
        question: "Which country is traditionally associated with kimchi?",
        options: ["South Korea", "Thailand", "China", "Vietnam"],
        answer: 0,
        explanation: "Kimchi is a traditional Korean fermented food.",
        level: 1,
    },
    {
        question: "In which country is pizza strongly associated with its traditional cuisine?",
        options: ["Italy", "Germany", "Greece", "Turkey"],
        answer: 0,
        explanation: "Pizza is one of the foods most strongly associated with Italian cuisine.",
        level: 1,
    },
    {
        question: "Which country is famous for fish and chips?",
        options: ["United Kingdom", "Canada", "Ireland", "Australia"],
        answer: 0,
        explanation: "Fish and chips is a classic British dish.",
        level: 1,
    },
    {
        question: "In which country is pho a traditional dish?",
        options: ["Vietnam", "China", "Japan", "Malaysia"],
        answer: 0,
        explanation: "Pho is a traditional Vietnamese noodle soup.",
        level: 1,
    },
    {
        question: "Which country is famous for maple syrup?",
        options: ["Canada", "Brazil", "Spain", "India"],
        answer: 0,
        explanation: "Canada is particularly famous for its maple syrup production.",
        level: 1,
    },
    {
        question: "Which country is traditionally associated with croissants?",
        options: ["France", "Italy", "Belgium", "Switzerland"],
        answer: 0,
        explanation: "Croissants are strongly associated with French cuisine and culture.",
        level: 1,
    },
    {
        question: "Which country is famous for traditional sushi?",
        options: ["Japan", "Peru", "Mexico", "Egypt"],
        answer: 0,
        explanation: "Sushi is one of the best-known foods in Japanese cuisine.",
        level: 1,
    },
    // ============================================================
    // LEVEL 2
    // ============================================================
    {
        question: "Where does couscous have its strongest traditional roots?",
        options: ["North Africa", "Northern Europe", "South America", "East Asia"],
        answer: 0,
        explanation: "Couscous has deep traditional roots in North African cuisine, especially in the Maghreb.",
        level: 2,
    },
    {
        question: "Which country is particularly associated with moussaka?",
        options: ["Greece", "Japan", "Brazil", "Morocco"],
        answer: 0,
        explanation: "Moussaka is strongly associated with Greek cuisine.",
        level: 2,
    },
    {
        question: "Which country is famous for the traditional dish bibimbap?",
        options: ["South Korea", "Thailand", "India", "Indonesia"],
        answer: 0,
        explanation: "Bibimbap is a traditional Korean rice dish.",
        level: 2,
    },
    {
        question: "Where is ceviche traditionally associated with?",
        options: ["Peru", "Germany", "Japan", "Canada"],
        answer: 0,
        explanation: "Ceviche is particularly associated with Peruvian cuisine.",
        level: 2,
    },
    {
        question: "Which country is famous for the dish tagine?",
        options: ["Morocco", "Norway", "Argentina", "Vietnam"],
        answer: 0,
        explanation: "Tagine is a traditional North African dish strongly associated with Morocco.",
        level: 2,
    },
    {
        question: "Which fruit is native to South America?",
        options: ["Pineapple", "Apple", "Peach", "Cherry"],
        answer: 0,
        explanation: "Pineapples originated in South America.",
        level: 2,
    },
    {
        question: "Which fruit is particularly associated with Southeast Asia and has a very strong smell?",
        options: ["Durian", "Pear", "Strawberry", "Peach"],
        answer: 0,
        explanation: "Durian is native to Southeast Asia and is famous for its strong smell.",
        level: 2,
    },
    {
        question: "Which country is particularly famous for its tradition of eating tapas?",
        options: ["Spain", "Austria", "Poland", "Sweden"],
        answer: 0,
        explanation: "Tapas are a well-known part of Spanish food culture.",
        level: 2,
    },
    {
        question: "Which country is traditionally associated with the dish pad thai?",
        options: ["Thailand", "Vietnam", "China", "India"],
        answer: 0,
        explanation: "Pad Thai is a famous Thai noodle dish.",
        level: 2,
    },
    {
        question: "Which country is particularly famous for the traditional drink mate?",
        options: ["Argentina", "France", "Japan", "Egypt"],
        answer: 0,
        explanation: "Mate is deeply rooted in the food culture of Argentina and several neighboring South American countries.",
        level: 2,
    },
    // ============================================================
    // LEVEL 3
    // ============================================================
    {
        question: "Which country has a strong traditional culture of eating insects such as crickets and grasshoppers?",
        options: ["Mexico", "Iceland", "Portugal", "Egypt"],
        answer: 0,
        explanation: "In several regions of Mexico, insects such as grasshoppers and other edible insects are traditional foods.",
        level: 3,
    },
    {
        question: "Which country is traditionally associated with the dish khachapuri?",
        options: ["Georgia", "Romania", "Lebanon", "Croatia"],
        answer: 0,
        explanation: "Khachapuri is a traditional Georgian cheese-filled bread.",
        level: 3,
    },
    {
        question: "Which country is traditionally associated with injera, a fermented flatbread?",
        options: ["Ethiopia", "Morocco", "Turkey", "India"],
        answer: 0,
        explanation: "Injera is a traditional fermented flatbread from Ethiopia.",
        level: 3,
    },
    {
        question: "Which country is traditionally associated with the dish feijoada?",
        options: ["Brazil", "Chile", "Spain", "Greece"],
        answer: 0,
        explanation: "Feijoada is a traditional Brazilian dish made with beans and meat.",
        level: 3,
    },
    {
        question: "Which country is traditionally associated with the fermented fish dish surströmming?",
        options: ["Sweden", "Finland", "Denmark", "Estonia"],
        answer: 0,
        explanation: "Surströmming is a traditional Swedish fermented Baltic Sea herring.",
        level: 3,
    },
    {
        question: "Which country is traditionally associated with the dish nasi goreng?",
        options: ["Indonesia", "Nepal", "Turkey", "Morocco"],
        answer: 0,
        explanation: "Nasi goreng is a traditional Indonesian fried rice dish.",
        level: 3,
    },
    {
        question: "Which country is traditionally associated with the cheese-making tradition behind halloumi?",
        options: ["Cyprus", "Austria", "Belgium", "Hungary"],
        answer: 0,
        explanation: "Halloumi is a traditional cheese strongly associated with Cyprus.",
        level: 3,
    },
    {
        question: "Which country is traditionally associated with the fermented cabbage dish sauerkraut?",
        options: ["Germany", "Portugal", "Japan", "Argentina"],
        answer: 0,
        explanation: "Sauerkraut is strongly associated with German cuisine and food traditions.",
        level: 3,
    },
    {
        question: "Which country is traditionally associated with the dish manti, small filled dumplings?",
        options: ["Turkey", "Brazil", "Ireland", "Thailand"],
        answer: 0,
        explanation: "Manti are dumplings strongly associated with Turkish cuisine, although similar dumplings exist across Central Asia and neighboring regions.",
        level: 3,
    },
    {
        question: "Which country is traditionally associated with the dish cevapi, small grilled minced-meat sausages?",
        options: ["Bosnia and Herzegovina", "Portugal", "Japan", "Peru"],
        answer: 0,
        explanation: "Cevapi are a traditional grilled meat dish strongly associated with Bosnia and Herzegovina and the wider Balkans.",
        level: 3,
    },
];